---
- hosts: localhost
  connection: local
  tasks:
  - name: Provisoning Rhel Instances in AWS
    local_action:
       module: ec2
       key_name: Thekey
       group_id: sg-007ab97f
       instance_type: t2.micro
       image: ami-b63769a1
       vpc_subnet_id: subnet-ef5510c2
       region: us-east-1
       assign_public_ip: yes
       wait: true
       count: 2
    register: aws_new_instance
     
  - name: Wait for the instances to boot by checking the ssh port
    wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
    with_items: '{{ aws_new_instance.instances }}'
     
  - name: ananth
    hosts: all
    become: true
    tasks:
      - name: Installing Webserver
        yum: name=httpd state=present update_cache=yes
      - name: starting apache2
        service: name=httpd state=started enabled=yes
      - name: Changing the Apache Listening port
        lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen" line="Listen {{ http_port }}"     
