---
- hosts: all
  become: true
  tasks:
   - name: Provisoning Rhel Instances in AWS
     ec2:
       aws_access_key: "AKIAJAKB6XVEDNP5RK2Q"
       aws_secret_key: "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"
       key_name: Funkey
       group_id: sg-007ab97f
       instance_type: t2.micro
       image: ami-b63769a1
       vpc_subnet_id: subnet-ef5510c2
       region: us-east-1
       assign_public_ip: yes
       wait: true
       count: 2
   - name: Installing Webserver
     yum: name=httpd state=present update_cache=yes
   - name: starting apache2
     service: name=httpd state=started enabled=yes
   - name: Changing the Apache Listening port
     lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen" line="Listen {{ http_port }}"
