---
- name: Terminate already existing instance
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-xxxxxx'
      - 'i-xxxxxx'
      - 'i-xxxxxx'
    region: us-east-1
  tasks:
    - name: Terminate the already existing instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        region: '{{ region }}'
        key_name: "{{ key }}"
        state: absent
        wait: True
        vpc_subnet_id: subnet-ef5510c2

- hosts: localhost
  connection: local
  tasks:
  - name: Provisoning Rhel Instances in AWS
    local_action:
       module: ec2
       key_name: "{{ key }}"
       group_id: sg-007ab97f
       instance_type: t2.micro
       image: ami-b63769a1
       vpc_subnet_id: subnet-ef5510c2
       region: us-east-1
       assign_public_ip: yes
       wait: true
       count: "{{ n }}"
    register: ec2
  
  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: "{{ gpname }}"
    with_items: "{{ ec2.instances }}"
   
  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
    
- name: "{{ gpname }}"
  hosts: all
  become: true
  tasks:
  - name: Installing Webserver
    yum: name=httpd state=present update_cache=yes
  - name: starting apache2
    service: name=httpd state=started enabled=yes
  - name: Changing the Apache Listening port
    lineinfile: dest=/etc/httpd/conf/httpd.conf regexp="^Listen" line="Listen {{ http_port }}"   
