---
- name: Apache
  hosts: all
  become: yes
  become_user: root
  become_method: su
  tasks:
    - name: Installing Webserver
      yum: name=httpd state=present update_cache=yes
    - name: starting apache2
      service: name=httpd state=started enabled=yes
